{
 "title": "Gateway",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Anchor Latency",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(gateway_sequencer_sim_latency_secs_bucket{method=\"anchor\"}[5m])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(gateway_sequencer_sim_latency_secs_bucket{method=\"anchor\"}[5m])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(gateway_sequencer_sim_latency_secs_bucket{method=\"anchor\"}[5m])))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Simulate Latency",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(gateway_sequencer_sim_latency_secs_bucket{method=\"simulate\"}[5m])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(gateway_sequencer_sim_latency_secs_bucket{method=\"simulate\"}[5m])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(gateway_sequencer_sim_latency_secs_bucket{method=\"simulate\"}[5m])))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Seal Latency",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(gateway_sequencer_sim_latency_secs_bucket{method=\"seal\"}[5m])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(gateway_sequencer_sim_latency_secs_bucket{method=\"seal\"}[5m])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(gateway_sequencer_sim_latency_secs_bucket{method=\"seal\"}[5m])))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Simulation Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "sum by(method, result) (rate(gateway_sequencer_sim_requests{}[5m]))",
     "legendFormat": "{{method}}-{{result}}"
    }
   ]
  },
  {
   "title": "L1 Sync Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "gateway_sequencer_l1_sync_time{}",
     "legendFormat": "L1 Sync Time"
    }
   ]
  },
  {
   "title": "Info",
   "type": "stat",
   "gridPos": { "h": 16, "w": 9, "x": 0, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gateway_info{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Block numbers",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gateway_blocks_l1{}", "legendFormat": "L1" },
    { "expr": "gateway_blocks_l2{}", "legendFormat": "L2 Preconf" },
    { "expr": "gateway_blocks_l2_origin{}", "legendFormat": "L2 Origin" }
   ]
  },
  {
   "title": "Gateway State",
   "type": "state-timeline",
   "gridPos": { "h": 15, "w": 13, "x": 0, "y": 68 },
   "targets": [
    { "expr": "gateway_sequencer_state{}", "legendFormat": "State" },
    {
     "expr": "gateway_sequencer_is_proposer{}",
     "legendFormat": "Proposer"
    },
    {
     "expr": "gateway_sequencer_is_sequencer{}",
     "legendFormat": "Sequencer"
    }
   ]
  },
  {
   "title": "Gas and Fees",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 14, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "gateway_blocks_gas_used{}", "legendFormat": "gas_used" },
    { "expr": "gateway_blocks_gas_limit{}", "legendFormat": "gas_limit" },
    { "expr": "gateway_blocks_base_fee{}", "legendFormat": "Base Fee" }
   ]
  }
 ]
}