app_id = "taiko_helder"

[l1]
name = "helder"
rpc_url = ""
ws_url = ""
beacon_url = ""

[l2]
name = "taiko"
rpc_url = "http://0.0.0.0:8545"
ws_url = "ws://0.0.0.0:8546"
taiko_token = "0x7368c574ef29Ee13e52Ca24c3FaEB4D8d45fDB3c"          # taikoTokenAddress
l1_contract = "0xA15933252102952D923197C26F144227097988B9"          # taikoInboxAddress
l2_contract = "0x1670100000000000000000000000000000010001"          # taikoAnchorAddress
router_contract = "0x2dD160d1791fbC5824b10c54A38CF2E11c8EdBd8"      # preconfRouterAddress
whitelist_contract = "0x9D2E8FFC93027D682485B3955737d9d56cbd7Bf6"   # preconfWhitelistAddress
wrapper_contract = "0x0000000000000000000000000000000000000000"     # taikoWrapperAddress

[gateway]
rpc_port = 10001
simulator_url = "http://0.0.0.0:8545"
l2_target_block_time_ms = 2_000
dry_run = false
# if gateway doesnt receive a new L1 block for this amount of time, stop sequencing
l1_delay_secs = 48                                                  
# wait until this many blocks have passed to check that the L1 propose tx hasnt reorged out
l1_safe_lag = 2 
coinbase = "0x591317B806B96262C07105CC06CB4831008AfDf2"
# Number of slots to wait before refreshing the anchor, the larger this is the more blocks we can fit in a batch, but we risk it getting stale when proposing
# This is on top of the l1_safe_lag above, so from the latest L1 blocks we keep blocks up to anchor_batch_lag + l1_safe_lag old
# This should be higher than delay_sequence_slots, so we avoid reorging the previous gateway
anchor_batch_lag = 16
soft_block_url = ""
status_url = ""
handover_window_slots = 4
handover_start_buffer_ms = 6_000
jwt_secret_path = "~/taiko-geth-gattaca/geth/jwtsecret"
# Number of simulators to run in parallel when sorting, higher means better blocks but more overhead
max_sims_per_loop = 5
# if there are more than this batches waiting to be proposed, throttle the block size
throttle_queue_target = 2
# block size will be throttled by (1 - factor)^(queue_size - target)
throttle_factor = 0.1
# when a batch exceeds this size in blobs we'll propose it immediately
blob_target = 3
# minimum priority fee to use for batch proposals in gwei
min_priority_fee = 1.0

builder_url = "https://rpc.builder.xyz"