app_id = "taiko_helder"

[l1]
name = "helder"
chain_id = 7014190335
rpc_url = "https://rpc.helder-devnets.xyz"
ws_url = "ws://18.199.195.154:8546"

[l2]
name = "taiko"
chain_id = 167010
rpc_url = "http://18.199.195.154:18545"                           # non-preconf rpc
ws_url = "ws://18.199.195.154:18546"                              # non-preconf ws
taiko_token = "0x6866A70100DeF26aF56e4A7A5e78F6eF3Ed5e5c2"        # taikoTokenAddress
l1_contract = "0x55FC9869E51885B6523D25d20A82A4bD9787998F"        # taikoInboxAddress
l2_contract = "0x1670100000000000000000000000000000010001"        # taikoAnchorAddress
router_contract = "0xcd1115B40120cCB7F233DC3B86c7D6Bb633c03d3"    # preconfRouterAddress
whitelist_contract = "0x896A084Add909028DCd92754D4408Acdfd11cbbc" # preconfWhitelistAddress

[gateway]
rpc_port = 10001
simulator_url = "http://0.0.0.0:8545"
propose_frequency_secs = 1
l2_target_block_time_ms = 2_000
coinbase = "0xB851706411c088A2c43e6AfCb2794be5dd2f2A51"
dry_run = true
use_blobs = false
force_reorgs = false
l1_delay_secs = 48
l1_safe_lag = 3
anchor_batch_lag = 8
soft_block_url = "http://0.0.0.0:9998/preconfBlocks"
