app_id = "taiko_helder"

[l1]
name = "helder"
chain_id = 7014190335
rpc_url = "https://rpc.helder-devnets.xyz"
ws_url = ""

[l2]
name = "taiko"
chain_id = 167010
rpc_url = ""                                                      # non-preconf rpc
ws_url = ""                                                       # non-preconf ws
taiko_token = "0xbB8D45E3FD2a5138d6569FedbBb75083349ce45E"
l1_contract = "0xA61a5ABD774Cb7aE5D4A2553990ea7fB253A315C"
l2_contract = "0x1670100000000000000000000000000000010001"
router_contract = "0x6631488A0A6Fd9d7926e90B1C658D1B4cc4953Da"
whitelist_contract = "0x9127086c3fb12fa764721C02Cc98C0F06206F82F"

[gateway]
rpc_port = 10000
simulator_url = "http://0.0.0.0:8545"
propose_frequency_secs = 180
l2_target_block_time_ms = 2_000
coinbase = "0xB851706411c088A2c43e6AfCb2794be5dd2f2A51"
dry_run = true
use_blobs = false
force_reorgs = false
anchor_input = "taiko preconfs"                         # this will be padded/truncated to 32 bytes
l1_delay_secs = 48
l1_safe_lag = 3
anchor_batch_lag = 8
soft_block_url = "http://0.0.0.0:9998/preconfBlocks"
