app_id = "taiko_helder"

[l1]
name = "helder"
chain_id = 7014190335
rpc_url = "https://rpc.helder-devnets.xyz"
ws_url = "ws://18.199.195.154:8546"

[l2]
name = "taiko"
chain_id = 167010
rpc_url = "http://18.199.195.154:18545"                             # non-preconf rpc
ws_url = "ws://18.199.195.154:18546"                                # non-preconf ws
taiko_token = "0xaDf33C22d0fB31bEA7861528A358C9cfD0E7AF98"          # taikoTokenAddress
l1_contract = "0xD1D5e6A666b7a41a775645fbFaB01bD2b4B29061"          # taikoInboxAddress
l2_contract = "0x1670100000000000000000000000000000010001"          # taikoAnchorAddress
router_contract = "0xFE28357BD8fFCD5f67b0E1276283Fc115941D0cF"      # preconfRouterAddress
whitelist_contract = "0x0045F84Ebed47f99552C8fEfFf8179A335b3473a"   # preconfWhitelistAddress

[gateway]
rpc_port = 10001
simulator_url = "http://0.0.0.0:8545"
propose_frequency_secs = 30
l2_target_block_time_ms = 2_000
coinbase = "0xB851706411c088A2c43e6AfCb2794be5dd2f2A51"
dry_run = false
use_blobs = false
force_reorgs = false
l1_delay_secs = 48                                                  # if gateway doesnt receive a new L1 block for this amount of time, stop sequencing
l1_safe_lag = 3
anchor_batch_lag = 0
soft_block_url = "http://18.199.195.154:9998/preconfBlocks"
# soft_block_url = "http://0.0.0.0:9999/preconfBlocks"
